# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1P3xLzjERNgc3RBHXtCfPOi16kykuWg
"""

# --- Imports ---
import time, tracemalloc
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.manifold import TSNE
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, ConfusionMatrixDisplay
)

RANDOM_STATE = 42

# --- Upload train.csv ---
from google.colab import files
uploaded = files.upload()  # click "Choose Files" and select train.csv
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)
print(df.shape)
df.head()

# --- Preprocess ---
X = df.drop(columns=["price_range"])
y = df["price_range"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# --- t-SNE plot ---
print("Running t-SNE...")
tsne = TSNE(n_components=2, perplexity=30, init="pca",
            learning_rate="auto", random_state=RANDOM_STATE)
embedding = tsne.fit_transform(X_scaled)

plt.figure(figsize=(8, 6))
classes = np.sort(y.unique())
cmap = plt.get_cmap("viridis", len(classes))
for i, cls in enumerate(classes):
    mask = y == cls
    plt.scatter(embedding[mask, 0], embedding[mask, 1], s=15,
                color=cmap(i), label=f"price_range = {cls}", alpha=0.8)
plt.title("2D t-SNE of Mobile Price Classification Feature Space")
plt.xlabel("t-SNE dimension 1")
plt.ylabel("t-SNE dimension 2")
plt.legend()
plt.tight_layout()
plt.savefig("tsne_plot.png", dpi=150)
plt.show()

# --- Train/test split ---
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
)

all_results = []

def evaluate_model(model, name):
    tracemalloc.start()
    start = time.perf_counter()
    model.fit(X_train, y_train)
    train_time = time.perf_counter() - start
    _, peak_mem = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average="macro", zero_division=0)
    rec = recall_score(y_test, y_pred, average="macro", zero_division=0)
    f1 = f1_score(y_test, y_pred, average="macro", zero_division=0)
    cm = confusion_matrix(y_test, y_pred)

    disp = ConfusionMatrixDisplay(confusion_matrix=cm)
    fig, ax = plt.subplots(figsize=(5, 5))
    disp.plot(ax=ax, colorbar=False, cmap="Blues")
    ax.set_title(f"Confusion Matrix: {name}")
    plt.tight_layout()
    plt.savefig(f"confusion_matrix_{name.replace(' ', '_').replace('/', '_')}.png", dpi=150)
    plt.show()

    print(f"[{name}] acc={acc:.4f} prec={prec:.4f} rec={rec:.4f} f1={f1:.4f} "
          f"time={train_time:.4f}s peak_mem={peak_mem/1e6:.2f}MB")

    all_results.append({
        "model": name, "accuracy": acc, "precision_macro": prec,
        "recall_macro": rec, "f1_macro": f1,
        "train_time_sec": train_time, "peak_memory_MB": peak_mem / 1e6
    })

# --- SVM: three kernels ---
for kernel in ["linear", "poly", "rbf"]:
    evaluate_model(SVC(kernel=kernel, random_state=RANDOM_STATE), f"SVM ({kernel} kernel)")

# --- Decision Tree: varying max_depth ---
for depth in [2, 4, 8, None]:
    label = f"DT max_depth={depth if depth is not None else 'None (full)'}"
    evaluate_model(DecisionTreeClassifier(max_depth=depth, random_state=RANDOM_STATE), label)

# --- Decision Tree: varying min_samples_split ---
for ms in [2, 10, 50, 100]:
    evaluate_model(DecisionTreeClassifier(min_samples_split=ms, random_state=RANDOM_STATE),
                    f"DT min_samples_split={ms}")

# --- Results table + comparison charts ---
results_df = pd.DataFrame(all_results)
results_df.to_csv("results.csv", index=False)
print(results_df.to_string(index=False))

def bar_chart(column, ylabel, title, fname):
    plt.figure(figsize=(9, 5))
    plt.bar(results_df["model"], results_df[column], color="steelblue")
    plt.ylabel(ylabel)
    plt.title(title)
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.savefig(fname, dpi=150)
    plt.show()

bar_chart("accuracy", "Accuracy", "Accuracy comparison across models", "compare_accuracy.png")
bar_chart("f1_macro", "F1-score (macro)", "F1-score comparison across models", "compare_f1.png")
bar_chart("train_time_sec", "Training time (s)", "Training time comparison", "compare_time.png")
bar_chart("peak_memory_MB", "Peak memory (MB)", "Peak memory comparison", "compare_memory.png")

import os
print(os.listdir("."))

from google.colab import files
files.download("results.csv")

files.download("tsne_plot.png")

files.download("compare_accuracy.png")

files.download("compare_f1.png")

files.download("compare_time.png")

files.download("compare_memory.png")

import os
for f in os.listdir("."):
    if f.startswith("confusion_matrix_"):
        files.download(f)

